# Generated by Django 2.2.4 on 2019-09-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=15)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_address', models.TextField()),
                ('user_privelage', models.TextField()),
                ('user_status', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
