# Generated by Django 2.2.4 on 2019-09-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_password',
            field=models.TextField(default=''),
        ),
    ]
