# Generated by Django 2.2.4 on 2019-09-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_users_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_password',
            field=models.CharField(max_length=100),
        ),
    ]
